---
abstract: 'Error::Pure module for simple print instead die.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  IO::Scalar: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Pure-NoDie
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Error::Pure::Utils: 0.09
  Exporter: 0
  List::MoreUtils: 0
  Readonly: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Error-Pure-NoDie
  homepage: https://github.com/michal-josef-spacek/Error-Pure-NoDie
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Error-Pure-NoDie
version: '0.05'
